export const SET_TOAST_MESSAGE = 'SET_TOAST_MESSAGE';
export const SET_ROOT_ACCESS_TOKEN = 'SET_ROOT_ACCESS_TOKEN';
export const SET_GLOBAL_LOADER = 'SET_GLOBAL_LOADER';
export const SET_TOAST_VISIBLE = '@root/SET_TOAST_VISIBLE';
